# Generated by Django 5.2.13 on 2026-05-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='taskboard.task')),
            ],
        ),
    ]
