# Generated by Django 5.2.14 on 2026-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0002_taskrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Doing', 'Doing'), ('Done', 'Done')], default='ToDo', max_length=10),
        ),
    ]
